version: '3.5'

services:
  rhit:
    build:
      context: .
    container_name: rhit
    volumes:
     - /var/nginx/log:/var/nginx/log
     - ./config.toml:/usr/local/cargo/.cargo/config
    stdin_open: true